# -*- coding: utf-8 -*-
"""class06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGojcY79dkUCHsItYhV0ZSTGuSF7Lx4P
"""



"""# conditional statement"""



"""# traffic light project using python conditional statement"""

light=input('enter light :')
if(light=='red'):
  print('stop')
elif(light=='yellow'):
  print('look')
elif(light=='green'):
  print('go')
else:
  print('light is broken')

"""# take a number and print its positive or negative

"""

num=int(input('enter number :'))
if(num>0):
  print('positive')
elif(num<0):
  print('negative')
else:
  print('zero')



"""# take a number and print it is ever or odd"""

num=int(input('enter number :'))
if(num%2==0):
  print('even')
else:
  print('odd')

"""# amra jannat e jabo naki jahanname jabo ta nirnoy er jonno code"""

amol=input('enter amol :')
if(amol=='namaj'):
  print('jannat')
elif(amol=='hajj'):
  print('jannat')
elif(amol=='jakat'):
  print('jannat')
elif(amol=='roja'):
  print('jannat')
else:
  print('jahannam')

