# -*- coding: utf-8 -*-
"""class04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iH8DEpbpOhpN0D_ub-aL1OeBBuHch0lD

# ami ekhane kivabe input niye kaj korte hoi ta bekkha korbo
"""

name=input('enter your name :')
print(name)

colege=input('college name :')
print(colege)

address=input('enter your address:')
print(address)

"""# q: take a two age of any two persons and print the total ages"""

age1=int(input('enter tanvir age :'))
age2=int(input('enter sumon age'))
total=age1+age2
print(age1)
print(age2)
print('total :',total)