# -*- coding: utf-8 -*-
"""class05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJnycFEbNj9pQHU0_d3EZ7Bpn3Jz8mxO
"""



"""# take a two input and print sum,sub,mul,div and remainder"""

num1=int(input('enter num1 :'))
num2=int(input('enter num2 :'))

sum=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2
rem=num1%num2

print(sum)
print(sub)
print(mul)
print(div)
print(rem)

"""# take a three number and print the sum with average of this number"""

num1=int(input('enter num1 :'))
num2=int(input('enter num2 :'))
num3=int(input('enter num3 :'))3

sum=num1+num2+num3
avg=sum/3

print(sum)
print(avg)

"""# take three float number and print their sum with average"""

